### ISSUE TITLE
how to download more clock images 

### ISSUE THREAD

**Issue by Moeenuddin178** [epegasus/ePegasus-Analogue-Live-Wallpaper#1]
hi brother I am wondering how you. make the images .
secondly what are the width height for making images .
can we download the clock images from any online website 
thanks

**Comment by epegasus** [comment]
Hello @Moeenuddin178, 

You can design images of 800*800 resolutions with an aspect ratio of 1:1.
For images, you may need to design such images with 4 different items (background, hour, minute, seconds)

**Comment by Moeenuddin178** [comment]
thanks brother
